### ISSUE TITLE
[提议]可以增加一个自动签到的功能吗

### ISSUE THREAD

**Issue by RemKeeper** [Yoroion/FuckMeetingPlus#1]
![image](https://user-images.githubusercontent.com/78486275/168982815-c8428d2c-e1d4-4223-99ef-5e34a9cd0b44.png)
这个签到

**Comment by Kyocius** [comment]
签到功能我们老师没有用过，所以我不太清楚它的逻辑...
是老师那端自己发起签到的吗？
还是说一进入会议就会签到？

**Comment by RemKeeper** [comment]
> 签到功能我们老师没有用过，所以我不太清楚它的逻辑...
> 是老师那端自己发起签到的吗？
> 还是说一进入会议就会签到？

由主持人发起的签到，初步判断是弹出一个网页，但是我拿Fiddler没抓出来。

**Comment by Kyocius** [comment]
> 由主持人发起的签到，初步判断是弹出一个网页，但是我拿Fiddler没抓出来。

如果签到功能是人为发起的，那么我可能不会给 FM+ 增加这个功能
