### ISSUE TITLE
依赖版占用内存大的问题

### ISSUE THREAD

**Issue by zxcsjf** [Yoroion/FuckMeetingPlus#2]
![屏幕截图 2022-06-12 091340](https://user-images.githubusercontent.com/59216999/173210252-ddf92581-d2ee-45d3-9c49-59836fc41e3a.jpg)
电脑是thinkbook14+，Windows 11 家庭中文版，操作系统版本22000.527，.NET 6.0.300, 内存是32gLPDDR5

**Comment by Kyocius** [comment]
我又测试了一下，内存占用实际和**屏幕分辨率**和**缩放百分比**有关
在 23 寸 1080P 100% 缩放下，内存占用在 50 MB 左右
应该是无解 ¯\\_ (ツ)_/¯
