### ISSUE TITLE
更好的自动入会解决方案

### ISSUE THREAD

**Issue by WetABQ** [Yoroion/FuckMeetingPlus#3]
https://github.com/SDLMoe/QQOnlineCourseBot/blob/master/src/main/kotlin/moe/sdl/qqonlinecoursebot/Utils.kt

**Comment by Kyocius** [comment]
感谢，已经采用了这个方法 https://github.com/Yoroion/FuckMeetingPlus/commit/7f168cf2c2b6ed7e47ce6c83b9107fb39d707b81 后续会重写 UI 部分
