### ISSUE TITLE
为什么运行的时候只能选择用微软商店打开

### ISSUE THREAD

**Issue by Softssiter** [Yoroion/FuckMeetingPlus#6]
到时间了它会打开应用 但是我不能选择 怎么解决这个问题呀
![微信图片_20221127232859](https://user-images.githubusercontent.com/103191657/204143483-a4190f0a-011f-4510-be18-43bb9210e0a9.png)

**Comment by Kyocius** [comment]
请问一下你有安装腾讯会议吗（

**Comment by Kyocius** [comment]
如果不提供详细信息，这条 Issue 将会被关闭。

**Comment by Softssiter** [comment]
我肯定装了腾讯会议 不然也不会用这个呀

**Comment by Kyocius** [comment]
请尝试重新安装腾讯会议，这并不是 FuckMeetingPlus 的问题...

**Comment by Softssiter** [comment]
好的 我再试试
